### PR TITLE
Updated the Kernel Source Path to the Linux home folder

### PR DESCRIPTION
**Pull request by dack-fe**

### CODE REVIEW

**Comment by tvannoy** [comment]
Previously, we have been "enforcing" all repos to be in the same root folder (which isn't necessarily a good idea anyway...). On Linux, having the kernel repo at the same level as the other repos works fine. That doesn't work on WSL, as you found. 

Do we want to make the convention that the kernel repo is always in a user's home folder, which will work in Linux and WSL, or add some logic to choose the kernel source path based on the host OS? 

At this point, I'd probably just go with needing the kernel repo to be in a user's home folder for simplicity. We still need to more fully address our path and installation issues, so it doesn't seem worthwhile to do much here without solving our larger path issues at the same time. Thoughts @fe-wickham @fe-tdavis?

**Comment by fe-wickham** [comment]
@tvannoy Yeah, this is being changed because of issues on Windows. If we want it to be somewhere else we can definitely update it later but for now this allows for it work for Connor and I. (I have had this change locally for a while)

**Review by fe-wickham — APPROVED** [review]
Those are some good changes

**Comment by tvannoy** [comment]
> @tvannoy Yeah, this is being changed because of issues on Windows. If we want it to be somewhere else we can definitely update it later but for now this allows for it work for Connor and I. (I have had this change locally for a while)

For sure. I figured you probably had that change locally already. Since all of our conventions are arbitrary so far, this is no less arbitrary haha. 

Additionally, Windows support should be the priority anyway, as I was the only Linux user, and anything that works on WSL will also work fine on Linux.

**Comment by fe-tdavis** [comment]
I'm good either way.  This seems fine for now.

**Pull request merged**
